name = "client"
version = "26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4a629418a2aa98dedeee211dda068b48cef3e8f275137dc888e651cad95d58c"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
