---
- name: Deploy to hostinger
  hosts: "{{ host | default('ubuntu') }}"
  become: true
 
  roles:
    - role: ufw

  handlers:
    - name: restart ssh service
      ansible.builtin.service:
        name: ssh
        state: restarted

  tasks:
    - name: update via apt
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: install tmux, vim, htop
      ansible.builtin.apt:
        name:
          - vim
          - tmux
          - htop
        state: present 
          
    - name: install docker
      block:
      - name: install required tools
        ansible.builtin.apt:
          name:
            - apt-transport-https
            - ca-certificates
            - curl
            - software-properties-common
            - python3-pip
          state: present

      - name: add docker GPG key 
        ansible.builtin.apt_key:
          url: "https://download.docker.com/linux/ubuntu/gpg"
          state: present

      - name: add docker apt repo
        ansible.builtin.apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
          state: present

      - name: install docker
        ansible.builtin.apt:
          name: docker-ce
          state: present
          update_cache: true

      - name: ensure docker service is running
        ansible.builtin.systemd:
          name: docker
          enabled: true
          state: started

    - name: create named users
      block:
      - name: create user cethien
        ansible.builtin.user:
          name: cethien
          comment: 'borislaw.sotnikow@gmx.de'
          shell: /bin/bash
          groups: 'sudo, docker'
          password: '$y$j9T$s/2hfsYA.NA.Xr2XJBxrJ0$AHdrr9u7l3Byi2IVjjg5fCr4qdYnf/h5OxbkKJrP6w9'
    
      - name: add public ssh key for cethien
        ansible.posix.authorized_key:
          user: cethien
          state: present
          key: "{{ lookup('file', 'keys/id_cethien.pub') }}"
   
    - name: setup ansible
      block:
      - name: create ansbile system user
        ansible.builtin.user:
          name: ansible
          system: true
          home: /var/lib/ansible
          shell: /bin/bash
          groups: 'sudo, docker'
          password: '$y$j9T$SIMkCIvu4mYN4NT5c3iqb/$X9Jzwzgve7I361gUvp.sL9pqUNJ/en/onPuPmAxytE2'

      - name: allow sudo with no password for user ansible
        community.general.sudoers:
          name: ansible
          user: ansible
          commands: ALL

      - name: add public ssh key for ansible
        ansible.posix.authorized_key:
          user: ansible
          state: present
          key: "{{ lookup('file', 'keys/id_ansible_hstgr.cloud.pub') }}"

    - name: ssh hardening
      block:
      - name: add file to /etc/ssh/sshd_config.d
        ansible.builtin.copy:
          src: '{{ playbook_dir }}/files/10-hardening.conf'
          dest: /etc/ssh/sshd_config.d/10-hardening.conf
        notify: restart ssh service      
