services:
  site:
    image: ghcr.io/potato-squad-de/potato-squad.de:latest
    environment:
      DISCORD_INVITE_URL: https://discord.gg/pHdZKq6mf9
    networks:
      - caddy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        caddy: potato-squad.de
        caddy.reverse_proxy: "{{upstreams 80}}"

        homepage.group: sites
        homepage.name: potato
        homepage.icon: potato.png
        homepage.description: OUT DOMAIN! LENA STINKT!
        homepage.href: https://potato-squad.de

networks:
  caddy:
    name: caddy_net
    external: true
