services:
  syncthing:
    # image: lscr.io/linuxserver/syncthing:latest
    image: syncthing/syncthing:latest
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
    environment:
      TZ: Europe/Berlin
    networks:
      - caddy
    volumes:
      # - config:/config
      - data:/var/syncthing
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        caddy: sync.cethien.me
        caddy.reverse_proxy: "{{upstreams 8384}}"

networks:
  caddy:
    name: caddy_net
    external: true

volumes:
    config:
      name: syncthing_config
    data:
      name: syncthing_data
