services:
  blocky:
    image: ghcr.io/0xerr0r/blocky:latest
    environment:
      TZ: Europe/Berlin
    ports:
      - 53:53/udp
    configs:
      - source: config.yml
        target: /app/config.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - caddy    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        homepage.group: services
        homepage.name: blocky
        homepage.icon: blocky.png
        homepage.description: FILTER ALL THE CRAP!

configs:
  config.yml:
    file: ./config.yml

networks:
  grafana:
    name: grafana_net
    external: true

  caddy:
    name: caddy_net
    external: true
