---
- name: ensure UFW is installed  
  when: ansible_facts['os_family'] == "Debian"
  notify: enable ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: reset UFW (if ufw_reset is true)
  when: ufw_reset | default(false)
  notify: enable ufw
  community.general.ufw:
    state: reset

- name: set default UFW incoming policy to deny
  community.general.ufw:
    default: deny
    direction: incoming

- name: set default UFW outgoing policy to allow
  community.general.ufw:
    default: allow
    direction: outgoing
      
- name: rate limit ssh connections
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: apply specific UFW rules
  when: rules is defined and rules | length > 0
  loop: "{{ rules | default([]) }}"
  community.general.ufw: "{{ item }}"

  # example: rules: [{ rule: allow, port: 80, proto: tcp }, { rule: deny, port: 23, proto: tcp }]
