---
- general:
    - github:
      - href: https://github.com/cethien
        icon: github.png

    - hostinger admin panel:
      - href: https://hpanel.hostinger.com/
        icon: hostinger.png
           
