services:
  cloudbeaver:
    image: docker.io/dbeaver/cloudbeaver:25.2.3
    volumes:
      - data:/opt/cloudbeaver/workspace
    networks:
      - caddy
      - cloudbeaver
    deploy:
      labels:
        caddy: cloudbeaver.cethien.home
        caddy.tls: internal
        caddy.reverse_proxy: "{{ upstreams 8978 }}"

        homepage.group: admin
        homepage.name: cloudbeaver
        homepage.icon: cloudbeaver.png
        homepage.href: https://cloudbeaver.cethien.home/
        homepage.description: sql deez nuts

volumes:
  data:
    name: cloudbeaver_data

networks:
  caddy:
    name: caddy_net
    external: true
  cloudbeaver:
    name: cloudbeaver_net
    attachable: true
    driver: overlay
