---
title: cethien.home
description: made by that jobless bro @ 2am on a tuesday
headerStyle: clean
target: _blank

background:
  image: https://mrwallpaper.com/images/hd/astronaut-pixel-art-h2pjux4bjskrw6fp.jpg
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

