services:
  dummy:
    image: luca3m/sleep:latest
    networks:
      - web
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        caddy: cethien.me
        caddy.redir: https://github.com/cethien

        homepage.group: sites
        homepage.name: cethien
        homepage.icon: cethien.png
        homepage.description: MY DOMAIN!
        homepage.href: https://cethien.me

networks:
  web:
    name: caddy_net
    external: true
