services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/data
    networks:
      - caddy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  caddy:
    name: caddy_net
    driver: overlay
    attachable: true

volumes:
  data:
    name: caddy_data
